title: "516 Hackers"
description: "Official site of 516 Hackers – ethical hacking, open-source projects, and community support."
logo: "https://avatars.githubusercontent.com/u/125684516?v=4"
favicon: "https://avatars.githubusercontent.com/u/125684516?v=4"

# Theme
theme: jekyll-theme-minimal

# Author
author:
  name: "516 Hackers Foundation"
  url: "https://github.com/516hackers"

# Social links
social:
  github: "https://github.com/516hackers"
  instagram: "https://www.instagram.com/516_hackers/"
  discussions: "https://github.com/516hackers/about/discussions"

# Navigation (appears in navbar / sidebar depending on theme)
nav:
  - name: "Home"
    link: /
  - name: "Mission"
    link: /mission
  - name: "History"
    link: /history
  - name: "Projects"
    link: /projects
  - name: "FAQ"
    link: /faq
  - name: "Community"
    link: /community
  - name: "Contact"
    link: /contact

# Footer
footer: >
  © 2025 516 Hackers Foundation · Built with ❤️ on [GitHub Pages](https://pages.github.com/).
