title: "516 Hackers"
description: "Official site of 516 Hackers – Ethical Cybersecurity Group helping victims of scams, hacked accounts, and blackmail. Always free of charge."
logo: "https://avatars.githubusercontent.com/u/125684516?v=4"
show_downloads: false

# Theme
theme: jekyll-theme-cayman

# Navbar quick links
nav:
  - title: "Home"
    url: /
  - title: "Mission"
    url: /mission
  - title: "History"
    url: /history
  - title: "Projects"
    url: /projects
  - title: "Community"
    url: /community
  - title: "FAQ"
    url: /faq
  - title: "Wiki"
    url: https://github.com/516hackers/about/wiki
  - title: "Discussions"
    url: https://github.com/516hackers/about/discussions

# Footer settings
footer:
  links:
    - title: "GitHub"
      url: https://github.com/516hackers
    - title: "Instagram"
      url: https://instagram.com/516_hackers
    - title: "Wiki"
      url: https://github.com/516hackers/about/wiki

# Plugins for extra features
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
