# ===============================
#  516 Hackers - GitHub Pages Config
# ===============================

title: "516 Hackers"
description: "Ethical Cybersecurity Collective | Mission, Projects & Community"
url: "https://516hackers.github.io"
baseurl: "/about"

# Theme
theme: jekyll-theme-cayman   # modern, colorful theme

# Logo & Branding
logo: "https://avatars.githubusercontent.com/u/125684516?v=4"
favicon: "https://avatars.githubusercontent.com/u/125684516?v=4"

# Social Links
social_links:
  github: https://github.com/516hackers
  instagram: https://www.instagram.com/516_hackers/
  discussions: https://github.com/516hackers/about/discussions

# Navigation
nav:
  - title: "Home"
    url: /
  - title: "Mission"
    url: /mission
  - title: "History"
    url: /history
  - title: "Projects"
    url: /projects
  - title: "FAQ"
    url: /faq
  - title: "Community"
    url: /community
  - title: "Contact"
    url: /contact

# SEO / Metadata
author: "516 Hackers Team"
keywords: "cybersecurity, hacking, ethical hackers, open-source, 516 hackers"
lang: en

# Footer
footer: >
  © 2025 516 Hackers – Ethical Cybersecurity Collective.  
  Built with ❤ on [GitHub Pages](https://pages.github.com).
