title: "516 Hackers"
description: "Official site of 516 Hackers – A legal cybersecurity and recovery foundation helping people protect accounts, recover scammed funds, and fight blackmail."
logo: "https://avatars.githubusercontent.com/u/125684516?v=4"
theme: jekyll-theme-slate

# GitHub Pages settings
show_downloads: false

# Social / Quick Links
social_links:
  github: https://github.com/516hackers
  instagram: https://instagram.com/516_hackers
  discussions: https://github.com/516hackers/about/discussions
  wiki: https://github.com/516hackers/about/wiki

# Navigation (top navbar)
nav:
  - name: "Home"
    link: /
  - name: "Mission"
    link: /mission
  - name: "History"
    link: /history
  - name: "Projects"
    link: /projects
  - name: "FAQ"
    link: /faq
  - name: "Community"
    link: /community

# Footer content
footer:
  copyright: "© 2025 516 Hackers – All Rights Reserved"
  note: "We provide legal cybersecurity help. We never charge money for recovery or support."
